### ISSUE TITLE
Naming alignment with PCM

### ISSUE THREAD

**Issue by maudnals** [WICG/conversion-measurement-api#173]
Follow-up from [PCM/#30](https://github.com/privacycg/private-click-measurement/issues/30): one attribute name isn't consistent across the Attribution Reporting spec and the PCM spec. 

- PCM uses [`attributionsourceid`](https://privacycg.github.io/private-click-measurement/#dom-htmlanchorelement-attributionsourceid)
- Attribution Reporting uses [`attributionsourceeventid`](https://github.com/WICG/conversion-measurement-api/blob/main/event_attribution_reporting_clicks.md#attribution-source-declaration)

Has this one fallen through the cracks or is there a reason why they're different? Do they have to be named differently due to the difference in data limitations?

**Comment by abebis** [comment]
Looking at the issue you linked it was intentional. 

> We would likely need another name for the low-entropy campaign ID. 

and

```
{
  "source-engagement-type" : <string>, // click or view
  "source-site" : <string>,
  "source-id" : <int>, // for PCM
  "source-event-id" : <int>, // for CM-API
  "attributed-on" : <string>,
  "trigger-data" : <int>,
  "version": <int>
}
```

@csharrison did not mention the reason but I guess that if it was a common attribute developers would have to align with the stricter (PCM) version and use a low-entropy id even on Chrome?

**Comment by csharrison** [comment]
Yes this was intentional, because it avoids the need to do user agent sniffing to support both API versions. It may be possible to be clever and use one ID for both systems as long as the ID is properly truncated in PCM, but the current spec for PCM says that inserting a too-big value will cause the API to fail:
https://privacycg.github.io/private-click-measurement/#ref-for-dom-htmlanchorelement-attributionsourceid

Closing this out but Maud feel free to re-open if you have any other suggestions.

**Comment by maudnals** [comment]
Great, thanks!
