### ISSUE TITLE
Consider using a non-JS based mechanism for generating aggregate histogram contributions

### ISSUE THREAD

**Issue by johnivdel** [WICG/conversion-measurement-api#194]
This is tracking the followup documented [here in the Aggregate Explainer.](https://github.com/WICG/conversion-measurement-api/blob/main/AGGREGATE.md#declarative--http-based-aggregation-triggering)

In the Aggregate Explainer, JavaScript access is required to invoke the attribution worklet and generate histogram contributions.

As noted in #100, "many existing measurement pings are HTTP only". This introduces disparity between where the Event-level API can be used and where the Aggregate API can be used.

We should work towards determining what a viable feature set for a potential declarative API would be in relation to the worklet capabilities.

Some of the features which can be achieved with the worklet include:
 - filtering conversions based on source-side information
 - having value be a function of impression and conversion side information
 - allowing buckets to be a function of impression and conversion side information

**Comment by johnivdel** [comment]
Adding some ideas for disccussion (derived from https://github.com/WICG/conversion-measurement-api/blob/main/meetings/2021-08-09-minutes.md)


**Intersections**
From @eriktaubeneck
Both the source and trigger side declare a set of buckets to contribute to (along with associated values). The browser takes the intersection of these buckets and reports histogram contributions.

Pros:
 * Simplicity
 * Some configurability

Cons:
 * potential combinatorial explosion of keys (the source needs to denote all the potential conversion side buckets which could be very fine-grained)

It's possible this could be extended to avoid the keys issue.

**Generic Matching**

We could extend this idea a bit further to provide some generic matching of buckets. Both the source and trigger could declare a set of "partial contributions" of the form:

```
[{
  "partial_bucket": int,
  "value": int                      // only set on trigger/conversion side
  "flags": [                         // controls how the browser will pair partial contributions
     name: <string>,
     value: [<string>, ...]
   ] 
},
... // more partial contributions
]
```

When the browser is given two sets of partial contributions for an impression and conversion, it will try and associate them together to form histogram contributions.

Matching could work as follows:
 
```
For each partial source contribution A:
  For each partial trigger contribution B:
    Check if A and B have the same set of flag names
    For each flag in A, verify the intersection of it's value with the same flag in B is non-empty
    If this is true for all flags, create a histogram contribution from A and B
```

This avoids a combinatorial explosion as the browser is summing the partial buckets to create the contribution.

Pros: 
  - Comparable configurability with the worklet (regarding the features above)
  - No script execution

Cons:
  - Increased complexity to the API's data model
  - Relatively verbose format

**Comment by eriktaubeneck** [comment]
Following up on the discussion today, here is another alternative to explore. Suppose that the reports were structured as a bit string, with the addition of `*  ` to denote "wildcard". 

For example, suppose that an source included the following JSON: (for simplicity, assume 8 bits instead of 32)

```json
source_contributions = [{
	"bucket": "101101**",
}]
```

and the event included the following JSON:

```json
event_contributions = [{
	"bucket": "10**0111",
	"value": 42,
}]
```

This would then constitute a "match" and would result in the following histogram contribution:

```json
histogram_contributions = [{
	"bucket": "10110111",
	"value": 42,
}]
```

To make this generically more explicit, we can think of taking two contributions, and merging them bit by bit with the following truth table:

|       | 0             | 1             | *    |
| ----- | ------------- | ------------- | ---- |
| **0** | 0             | Fail to match | 0    |
| **1** | Fail to match | 1             | 1    |
| **\*** | 0             | 1             | ?    |

`*,*` could result in 0, 1, or both. Another option would be to allow one side to specify `0*` and `1*`, where this value would always match, and only default to the value when the other side is `*`, i.e. the following truth table:

|       | 0             | 1             | 1*   | 0*   |
| ----- | ------------- | ------------- | ---- | ---- |
| **0** | 0             | Fail to match | 0    | 0    |
| **1** | Fail to match | 1             | 1    | 1    |
| **\*** | 0             | 1             | 1    | 0    |

My intuition is that it would be as expressive as **Generic Matching** option above, but that would be wrong. It would be *simpler* in terms of data structure/communication, but might be slightly more complicated to work with, in that it's a lower level abstraction.

**Comment by eriktaubeneck** [comment]
## Open Issues with both approaches

In addition to the suggestion above, I also wanted to capture a few of the open items that were mentioned:

1. Can source contribution match to multiple event contributions, and visa versa?
   1. My assumption is yes, i.e. you may want to have a contribution which is a count, and one which is a value, which are both linked to the same source contribution but the value is provided separately across two event contributions. **Note:** this could lead to an explosion in histogram contribution, up to the product of source and event contributions.
2. If there is a maximum number of contributions, and more are created by one of the above processes, what subset is taken?
   1. One option is to include a priority on one or both sides of the contributions (i.e. source, event, or both.) In the case of both, some way to combine the two (such as multiplying them) would need to be specified.
   2. Another option would be to rely on the budget usage to signal priority, assuming that a larger budget usage would indicate higher priority.
3. How is the budget usage determined in a declarative model?

**Comment by johnivdel** [comment]
> Following up on the discussion today, here is another alternative to explore. Suppose that the reports were structured as a bit string, with the addition of * to denote "wildcard".

I need to think a bit more on the exact capabilities of this idea. I think one issue I see is that any filtering criteria will need to be present in the bucket, which seems fairly limiting.

For example, if we consider the types of filtering discussed in #32:

> “Only count conversions where the product is one of [12345, 23456, 34567, …]”
> “how many people bought school-supplies after clicking on the ad promoting school supplies?”

This is possible in the proposed worklet API, but not possible with bit by bit matching as far as I can tell.

I have a few ideas for incorporating this approach with the Generic Matching option, specifically using some of the ideas discussed on #32 to give more worklet-like flexibility.

The following example shows how to compute a histogram of the form (assuming 8 bits instead of 32 for simplicity):

3 bit campaign x 1 bit "count or value" x 3 bit conversion type x 1 bit "was product advertised" 

The source side provides some data:

```
{
  source_labels: ["1011****", "1010****"]
  source_data: {  // arbitrary dictionary of data to control conversion side behavior
    product: [12345, 23456, 34567, …],
    conversion_subdomain: ["electronics.megastore", "electronics2.megastore"]
  }
}
```

source_labels is a list of histogram buckets which encode the impression side portion of the bucket. 

The trigger side will provide data of the form:

```
{
  attribution_filters: [ 
    conversion_subdomain: "electronics.megastore"
    directory: "/store/electronics" // Not set on the source side, so this key is ignored
  ],
  trigger_labels: [
    {
       label: "****101*", // This label encodes 3 bit conversion type
       source_labels: [0,1] // Add this trigger label to both source labels
    },
    {
       label: "*******1", // Represents that product was advertised
       source_labels: [0,1],
       filters: { product: 12345 }. // Only include this label if the product 12345 was in the source_data
    },
    {
       label: "*******0", // Product wasn't advertised
       source_labels: [0,1],
       not_filters: { product: 12345 }  // Only include this label if the product 12345 was *not* in the source_data
    },
  ],
  values: [1, 1000] // What values to use for the resulting buckets
}
```

attribution_filters allows you to control whether this conversion should count for the impression at all. In this case,
"electronics.megastore" was present on both the trigger/source data, so the trigger will be attributed to the source.

The browser then combines all of the trigger labels with source labels. To combine them, the browser will OR each source_label with each trigger_label whose filters match the source_data.

In the example above, the following two contributions are created:

bucket: 1011**** || ****101\* || *******1 -> 10111011
value: 1

bucket: 1010**** || ****101\* || *******1 -> 10101011
value: 1000

**Comment by alois-bissuel** [comment]
Thanks @johnivdel for the very clear presentation of last Monday (with the corresponding [slides](https://docs.google.com/presentation/d/1rTJA_m1cPpLNXrI6WZC_PlBAmqY3ZqUZPYAGJBa-5vc/edit#slide=id.p)).

I clearly see the value of having a declarative API for users who cannot integrate JS code, though it seems keeping the "generative" JS API is necessary for the more advanced use of the API, especially around ML. 

On top of my head, I see a couple of cases: 
- declaring a lot of contributions to the histogram, if the small limit of 3 is overridden (tentatively linking #249)
- complicated encoding of the features

Overall, this declarative API might be sufficient (and even better than the JS one) for simple reporting, but might be constraining too much for some advanced use cases.

**Comment by csharrison** [comment]
I am trying to think of the best way to unify event-level and aggregate reporting mechanisms under this mechanism.

Source declaration is fairly simple, and just adds a single new field: `source_event_id`.
```
// source declaration
{
  // source_event_id is only applicable to event-level reports.
  source_event_id: "12340873456",
  // source_labels ignored for event-level reports.
  source_labels: [...],
  // Data which is used for filtering later on
  source_data: {
    product: [12345, 23456, 34567, …],
    conversion_subdomain: ["electronics.megastore", "electronics2.megastore"]
  }
}
```
For triggers, there is a bit more choices:
1. Should we share `attribution_filter`s? It seems easiest for predictability to do so, but offers less flexibility if folks want to measure different things with aggregate / event-level reports.
2. Should we share the `trigger_labels`? Since event-level reports cannot contribute to multiple buckets it might make sense not to, since there may be different filtering logic applied
2. If we ever add "value" to event-level reports, how should it be done? Since event-level reports cannot contribute to multiple buckets, we might want to rename the `values` field above.
3. Do we want to make CTCs vs VTCs explicit in the format? Right now in the explainers they get different bit limits.

Here is one possible format that answers the above questions:
```
{
  // SHARE attribution_filters. This simplifies implementation and improves predictability since event and aggregate
  // are attributed in the same way 
  attribution_filters: [ 
    conversion_subdomain: "electronics.megastore"
    directory: "/store/electronics" // Not set on the source side, so this key is ignored
  ],
  // SEPARATE trigger data, since likely aggregate will have much more complex logic, it seems easier to split out
  aggregate_trigger_data: [
    {
       label: "****101*", // This label encodes 3 bit conversion type
       source_labels: [0,1] // Add this trigger label to both source labels
    },
    {
       label: "*******1", // Represents that product was advertised
       source_labels: [0,1],
       filters: { product: 12345 }. // Only include this label if the product 12345 was in the source_data
    },
    {
       label: "*******0", // Product wasn't advertised
       source_labels: [0,1],
       not_filters: { product: 12345 }  // Only include this label if the product 12345 was *not* in the source_data
    },
  ],
  aggregate_values: [1, 1000] // What values to use for the resulting buckets
  
  //  Separate event / navigation source data so that bit restrictions can be done syntactically and not dynamically.
  event_trigger_data: [
    {
      navigation_source_data: "101", // Enforces 3 bit
      filters: {product: 12345}
    },    
    {
      event_source_data: "1", // Enforces 1 bit label
      filters: {product: 12345}
    }
  ]
}
```

**Comment by csharrison** [comment]
One issue @linnan-github pointed out is that this mechanism does not compose well with response-based registration proposal (https://github.com/WICG/conversion-measurement-api/issues/261) because structured headers do not support such complicated nested formats.
https://datatracker.ietf.org/doc/html/rfc8941


We have basically a few options:
1. Deliver this JSON as part of the response body
1. Encode the format as a header with something like base64, or raw JSON with restrictions (like no CR and LF chars)
1. Rewrite the declarative mechanism to unnest, possibly by utilizing multiple headers

I think (1) would invalidate the mechanism in #261:
> We could potentially allow redirects within the attribution request to each specify their own Register-Attribution-Source.

So I think we are left with either (2) or (3). To me, (2) is non-ideal just from a purity standpoint, and it feels wasteful to have to encode/decode with base64. Here's a sketch of how 3 could work:

Structured headers support nesting to 3 levels
- Dictionary
  - Item array
    - Item
      - Item param 1
      - Item param 2
     - Item
   
This adds a lot of constraints on the design but it is maybe manageable, especially if we add another layer of nesting with separate HTTP headers:
```
Attribution-Reporting-Filters: <Dictionary of bare items>

Attribution-Reporting-Aggregate-Values: <List of integers>

Attribution-Reporting-Aggregate-Trigger-Data:  <
  List of Inner List of Item where Item is the source labels
  Each inner list is parametrized by a series of filters e.g. (product=12345) and a label=<string>

Attribution-Reporting-Event-Trigger-Data: <
  List of Item where Item is the trigger data
  parametrized by a series of filters e.g. (product=12345) and a bit about navigation vs. event sources
>
```
It seems like the above might work, although it is very ugly. This might be acceptable if we can make the aggregate and event headers aligned in terms of what is the Item and what are the parameters. The list of source labels is the only thing that makes them different. I tried above to support them natively with structured headers vs. some custom format in a bare string Item or byte sequence (e.g. encoding the source labels as a 128 bit-string or something).

cc @clelland who might have some opinions about use of structured headers and whether a kludge of this kind is appropriate or whether we should stick to something like (2) base64 json.

**Comment by johnivdel** [comment]
> Each inner list is parametrized by a series of filters e.g. (product=12345) and a label=<string>

From my understanding, we would not be able to have a filter use a list as it's value in this construction, is that right? 

I think for Attribution-Reporting-Filters: it would work if we used a dict of inner lists. I can't think of a reasonable way to encode the Aggregate-Trigger-Data as each label contains two types of lists: source_labels and filter values.

**Comment by csharrison** [comment]
> From my understanding, we would not be able to have a filter use a list as it's value in this construction, is that right?

You can't use a List, but you can set a bunch of parameters, so I was saying that each parameter would be a separate filter. This would be workable as long as we don't need any other kinds of parameters.

**Comment by clelland** [comment]
(2) is definitely ugly, although there is precedent for JSON header values (See [Report-To](https://www.w3.org/TR/2018/WD-reporting-1-20180925/#header), for instance, and the [abandoned JFV proposal](https://tools.ietf.org/id/draft-reschke-http-jfv-08.html) in general)

I'd prefer to see something structured used here. I need to look more closely at this example, but one possibility if a list of dicts or a dict of dicts is required could be to use structured keys -- for example, you can collapse

    { a: { x: 5, y: 2, z: "abc"},
      b: { x: 3, y: 0, z: "def"}}

into

    { a.x: 3, a.y: 2, a.z: "abc", b.x: 3, b.y: 0, b.z: "def"}

which works with the SF constraints.

**Comment by maudnals** [comment]
+1 to a structured header, this would improve developer experience.

**Comment by csharrison** [comment]
We ended up going with JSON headers, as we are introducing a lot of complicated nesting that was very difficult to manage with structured headers. I'm also going to close this issue because we landed on this solution and it is the one currently outlined in the explainer.
