### ISSUE TITLE
Aggregation Service: Clarification: Sending large amounts of data to the helper servers?

### ISSUE THREAD

**Issue by JonathanAquino-NextRoll** [WICG/conversion-measurement-api#255]
[This part](https://github.com/WICG/conversion-measurement-api/blob/main/SERVICE.md#sending-data-directly-to-the-helper-servers) of the documentation implies that the helper servers will not hold data for future queries. And as the reports are encrypted, we do not know which reports to send with a query for a given date range. Just to clarify: Each day, will we need to send a large amount (possibly 2 weeks’ worth, or several gigabytes) of encrypted reports to cover all the reports that the query is interested in?

**Comment by csharrison** [comment]
(Sorry for the delay on this response). Yes that's the idea with the current design. You'd batch most of your data and send it to the service which processes the reports in some fixed manner.

However, you wouldn't necessarily be sending 2 weeks worth of data every day, since that would entail querying the same record ~14 times (see [this note](https://github.com/WICG/conversion-measurement-api/blob/main/AGGREGATE.md#:~:text=Note%3A%20The%20design%20for%20the%20aggregation%20service%20also%20requires%20some%20amount%20of%20budgeting%20to%20ensure%20records%20aren%E2%80%99t%20processed%20too%20many%20times) in the explainer). It would likely be more efficient to perform queries over only a single day range and then make 2-week queries over the daily rollups.

**Comment by JonathanAquino-NextRoll** [comment]
OK thanks!
