### ISSUE TITLE
Understanding eTLD+1 and conversiondestination 

### ISSUE THREAD

**Issue by kevin-margueritte** [WICG/conversion-measurement-api#87]
Hi 👋 , thank you for this api proposal.
Concerning the documentation :
```
An impression is an anchor tag with special attributes:
<a conversiondestination="[eTLD+1]" impressiondata="[string]" impressionexpiry=[unsigned long long] reportingorigin="[origin]">
```
An impression could be stored if eTLD+1 of the ad click destination is equal to conversiondestination attribute. Therefore, an ad which lands to https://shop.advertiser.com with conversiondestination equals to https://advertiser.com should trigger an impression, if I’m not mistaken. However, I tried this use case and I was unable to trigger an impression.
I took a look in chromium repository and I believe that the whole origin is checked for the conversiondestination => https://source.chromium.org/chromium/chromium/src/+/master:content/browser/conversions/conversion_host.cc;drc=db9ae7941adc1d95c943accce9e0151d265fd640;l=152
I noticed you switched from eTLD+1 to origin for reportingorigin months ago, did you forget to do the same for conversiondestination ?

**Comment by maudnals** [comment]
Hi Kevin, thanks for your question!

You're correct that at the moment, the conversion destination is an [**origin**](https://web.dev/conversion-measurement/#ad-click-(steps-1-to-5):~:text=the%20origin%20where%20a%20conversion%20is%20expected%20for%20this%20ad.), not an eTLD+1.
Unless I'm mistaken, the Chrome Eng team designing the API is considering switching this to an [eTLD+1](https://web.dev/conversion-measurement/#what-else-may-change-in-future-iterations) at some point in the future.
We'll update the [README](https://github.com/WICG/conversion-measurement-api/blob/master/README.md), since IMU the paragraph you've extracted doesn't reflect the current state of the API. So, thanks fo the catch.

Feel free to continue posting questions / opening issues here as you go and build your prototype, we'll be happy to help!

CC @csharrison @johnivdel

**Comment by maudnals** [comment]
Update on this: a [fix](https://bugs.chromium.org/p/chromium/issues/detail?id=1131624) is being implemented

**Comment by maudnals** [comment]
Closing this, since the question has been answered.
For posterity: implementation and Chrome-specific questions should be directed to the [mailing list](https://groups.google.com/u/1/a/chromium.org/g/attribution-reporting-api-dev).
