### ISSUE TITLE
Support VTC in the event-level API

### ISSUE THREAD

**Issue by csharrison** [WICG/conversion-measurement-api#98]
The event-level API provides data that could not be achieved by the aggregate API. Currently it only support clicks, but we should consider what privacy mitigations are necessary to allow support for views as well, if possible.

One challenge with views is that they introduce a new form of information that clicks do not: exposed browsing history of the user. With a click conversion, the fact that a user clicked through and visited the advertiser's site is _known even without the API_ just by the fact that the user clicked on the ad. This piece of the user's browsing history is not private relative to the clicking context.

However, this all changes with a VTC API where not what sites the user converts on possibly reveals bits and pieces of the user's browsing history. This unique aspect requires us to be more careful when adding VTCs to an event-level API. Additionally, the fact that the API no longer requires any user activation gating means existing attacks become easier to pull off.

Possible (non-exhaustive) mitigations we could consider:
 - Event noising of some kind ([1](https://github.com/WICG/conversion-measurement-api/#speculative-adding-noise-to-the-conversion-event-itself), [2](https://github.com/WICG/conversion-measurement-api/issues/84))
 - More restrictive [rate limiting / API cooldowns](https://github.com/WICG/conversion-measurement-api/#reporting-cooldown)
 - Some mechanism like a cap of pending impression advertisers (per publisher) to avoid the attack of "seeding" many false impressions (like the Alexa top K) to try to learn the user's browsing history
 - Removing "multi-touch" attribution by only attributing a single last-touch impression
 - Stricter limits on the number of conversions that can be attributed to a single view

**Comment by eriktaubeneck** [comment]
Another attack to consider, similar to the "seeding" attack, but to learn the exact conversion value:

1. Publisher `publisher.com` runs advertising campaign with id `14` for advertiser `advertiser.com`.
2. When a user visits `publisher.com`, publisher actually registers views for 16 different campaign ids `[140, 141, ..., 14f]`. 
3. If and when that user converts, conversion events with value `v` now fire for all 16 campaign ids, each with DP applied so that ~1 events' value changes to `v'`.
4. Publisher observes ~15 `v` and ~1 `v'`, and concludes that `v` is the true value.

Now, this could be mitigated by limiting the number of impressions which can be attributed to a conversion, especially from the same publisher. However, consider the addition of something like an `item_id` for an advertiser who has a large catalog. Now, if the publisher and advertiser collude, step 3 can now become:

3. If and when that user converts, advertiser sends a conversion event for item `[0, 1, ..., f]` all with value `v`. Again, with DP applied, ~1 events' value changes to `v'`.

As you mention, we can consider things like rate limiting and API cooldowns, and using 4 bits here might be overly extreme. However, if n malicious views that can be sent causes a 1/n reduction in privacy (i.e. epsilon increases by a factor of n.)

**Comment by csharrison** [comment]
Thanks Erik. To summarize I think you're describing two attacks:

1. Send multiple conversions using a "multi-touch attribution" feature where multiple impressions attribute to a single conversion. Multi-touch attribution does not compose well with the event noising. I didn't mention it in the original issue but I think we would need to remove the "0 credit" impressions from being reported and only report the last-touch if we implement event-level VTC. This aligns with your mitigations.
2. Send multiple conversions attributing by attributing multiple conversions to a single (or fewer) impressions. Currently in the event-level API we restrict this to 3, but I could imagine stricter limits for VTC

Rate limits / cooldowns help here but I agree with you that we probably want some protections so that adversaries can't trivially reach the limit any time they want.

**Comment by eriktaubeneck** [comment]
1. I'm not sure you even need to limit it to just last-touch, I think it would be sufficient apply the DP to the conversion value across all impressions which are assigned any credit.
2. Yes, we should keep how this type of attack might reduce the privacy guarantees.

There is a third attack I have in mind, but it's more in anticipation of a feature that will likely be requested. Suppose the advertiser is _big box advertiser_ which has a very large catalog, and they want to run an ad (and measure attribution) for individual items. This could be accomplished by having both publisher and advertiser include an `item_id`, and then only trigger attribution when those match. 

IF we had that additional functionality, then you could essentially replicate a single view maliciously into multiple, and degrade the privacy guarantees. I'm not suggestion we should/would add this functionality, however I will point out that in the click-through scenario we wouldn't have this issue.

**Comment by johnivdel** [comment]
VTC support now has it's own [explainer](https://github.com/WICG/conversion-measurement-api/blob/main/event_attribution_reporting.md)

Future discussions regarding VTC support should move to targeted issues referencing the material in the explainer.
